name: publish

on:
  push:
    branches: [ main ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/ 
      - run: npm ci
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
#   publish-github:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: '12.x'
#         registry-url: 'https://npm.pkg.github.com'
#     - run: npm install
#     - run: npm publish
#       env:
#         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
